language: python
cache: pip

python:
  - "3.5"
  - "2.7"

env:
  - DJANGO="django>=1.11,<1.12"
  - DJANGO="django>=2.1,<2.2"
  - DJANGO="django>=2.2,<2.3"

matrix:
  exclude:
   - python: "2.7"
     env: DJANGO="django>=2.1,<2.2"
   - python: "2.7"
     env: DJANGO="django>=2.2,<2.3"

branches:
  only:
    - master

install:
  - pip install $DJANGO
  - python setup.py -q develop
  - pip install -r requirements-test.txt

script:
  - openwisp-utils-qa-checks --migration-path "./openwisp_network_topology" --migration-module topology
  - coverage run --source=openwisp_network_topology runtests.py

after_success:
  coveralls
