language: python
cache: pip

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="django>=2.2,<3.0"
  - DJANGO="django>=3.0,<3.1"

branches:
  only:
    - master

before_install:
  - pip install $DJANGO
  # TODO: remove when openwisp-utils 0.5.2 is released
  - pip install -U https://github.com/openwisp/openwisp-utils/tarball/master#egg=openwisp_utils[qa]

install:
  - python setup.py -q develop
  - pip install -r requirements-test.txt

script:
  - coverage run --source=openwisp_network_topology runtests.py
  - ./run-qa-checks
  # SAMPLE tests do not influence coverage, so we can speed up tests with --parallel
  - SAMPLE_APP=1 ./runtests.py --parallel --keepdb

after_success:
  coveralls
