# Generated by Django 3.2.18 on 2023-03-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0016_alter_topology_parser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topology',
            name='parser',
            field=models.CharField(
                choices=[
                    ('netdiff.OlsrParser', 'OLSRd (txtinfo/jsoninfo)'),
                    ('netdiff.BatmanParser', 'batman-advanced (jsondoc/txtinfo)'),
                    ('netdiff.BmxParser', 'BMX6 (q6m)'),
                    ('netdiff.NetJsonParser', 'NetJSON NetworkGraph'),
                    ('netdiff.CnmlParser', 'CNML 1.0'),
                    ('netdiff.OpenvpnParser', 'OpenVPN'),
                    ('netdiff.WireguardParser', 'Wireguard'),
                    ('netdiff.ZerotierParser', 'Zerotier'),
                ],
                help_text='Select topology format',
                max_length=128,
                verbose_name='format',
            ),
        ),
    ]
